from database import boletas, configuracion, facturas, login_intentos, rifas, traslados, usuarios, vendedores
from motores.config_service import get_config
from motores.constants import MOV_PAGO, MOVIMIENTOS_FIELD
from motores.payment_service import build_boletas_info_snapshot
from motores.ticket_service import sync_ticket_statuses

# Required indexes per collection: list of (key_spec, name)
# key_spec is a dict ({"campo": 1|-1}) or a plain string field name.
REQUIRED_INDEXES = {
    "boletas": [
        ({"rifa_id": 1, "_id": 1}, "rifa_id_1__id_1"),
        ({"vendedor_id": 1, "_id": 1}, "vendedor_id_1__id_1"),
        ({"estado": 1, "_id": 1}, "estado_1__id_1"),
        ({"total_abonado": 1, "_id": 1}, "total_abonado_1__id_1"),
        ({"vendedor_id": 1, "estado": 1}, "vendedor_id_1_estado_1"),
        ({"historial_movimientos.fecha": 1}, "historial_movimientos.fecha_1"),
        ({"cliente.telefono": 1}, "cliente.telefono_1"),
        ({"cliente.nombre": 1}, "cliente.nombre_1"),
        ({"historial_movimientos.metodo": 1}, "historial_movimientos.metodo_1"),
        ({"historial_movimientos.referencia": 1}, "historial_movimientos.referencia_1"),
        ({"historial_movimientos.tipo": 1}, "historial_movimientos.tipo_1"),
        ({"historial_movimientos.factura_id": 1}, "historial_movimientos.factura_id_1"),
        ({"historial_movimientos.traslado_id": 1}, "historial_movimientos.traslado_id_1"),
        ({"fecha_adquisicion": 1}, "fecha_adquisicion_1"),
    ],
    "vendedores": [
        ({"telefono": 1}, "telefono_1"),
    ],
    "facturas": [
        ({"fecha": -1}, "fecha_-1"),
        ({"tipo": 1}, "tipo_1"),
        ({"cliente.nombre": 1}, "facturas_cliente_nombre_1"),
        ({"vendedor_nombre": 1}, "facturas_vendedor_nombre_1"),
        ({"vendedor_id": 1}, "facturas_vendedor_id_1"),
        ({"estado": 1}, "facturas_estado_1"),
        ({"estado": 1, "creada_en": 1}, "facturas_estado_1_creada_en_1"),
        ({"tipo": 1, "fecha": -1}, "facturas_tipo_1_fecha_-1"),
    ],
    "rifas": [
        ({"estado": 1}, "estado_1", {"unique": True, "sparse": True}),
    ],
    "traslados": [
        ({"fecha": -1}, "fecha_-1"),
        ({"boleta_origen": 1}, "boleta_origen_1"),
        ({"boleta_destino": 1}, "boleta_destino_1"),
    ],
    "usuarios": [
        ({"usuario": 1}, "usuario_1"),
        ({"rol": 1}, "usuarios_rol_1"),
    ],
}

COLLECTIONS = {
    "boletas": boletas,
    "vendedores": vendedores,
    "facturas": facturas,
    "rifas": rifas,
    "configuracion": configuracion,
    "traslados": traslados,
    "usuarios": usuarios,
}


def _normalize_key(key):
    if isinstance(key, str):
        key = {key: 1}
    return frozenset(dict(key).items())


def _existing_index_keys(collection):
    try:
        return {frozenset(dict(doc["key"]).items()) for doc in collection.list_indexes()}
    except Exception as exc:
        print(f"  Error al listar índices de {collection.name}: {exc}")
        raise


def _autogenerated_name(key_spec):
    name = "_".join(f"{field}_{direction}" for field, direction in _normalize_key(key_spec).items())
    return name


def verificar_indices(crear: bool = True) -> bool:
    if boletas is None:
        raise RuntimeError("No hay conexión activa a MongoDB.")

    total_presentes = 0
    total_creados = 0
    fallidos = []

    for nombre_col, collection in COLLECTIONS.items():
        if collection is None:
            if crear:
                print(f"[SKIP] {nombre_col}: colección no disponible.")
            continue
        required = REQUIRED_INDEXES.get(nombre_col, [])
        if not required:
            continue
        existing = _existing_index_keys(collection)
        for entry in required:
            key_spec, expected_name = entry[0], entry[1]
            options = entry[2] if len(entry) > 2 else {}
            normalized = _normalize_key(key_spec)
            if normalized in existing:
                total_presentes += 1
                if crear:
                    print(f"[OK]   {nombre_col}.{expected_name}")
                continue
            if not crear:
                fallidos.append(f"{nombre_col}.{expected_name}")
                continue
            try:
                collection.create_index(dict(normalized), name=expected_name or _autogenerated_name(key_spec), **options)
                total_creados += 1
                print(f"[+NUEVO] {nombre_col}.{expected_name}")
            except Exception as exc:
                fallidos.append(f"{nombre_col}.{expected_name}: {exc}")
                print(f"[ERROR] {nombre_col}.{expected_name}: {exc}")

    if crear:
        print(f"\nÍndices verificados: {total_presentes} presentes, {total_creados} creados.")
    if fallidos:
        if crear:
            print(f"Índices con error ({len(fallidos)}):")
            for error in fallidos:
                print("  -", error)
        return False
    return True


def backfill_boletas_info() -> int:
    """Add static boletas_info snapshots to legacy cliente invoices missing them."""
    config = get_config()
    valor_boleta = int(config.get("valor_boleta", 10000) or 10000)
    count = 0
    cursor = facturas.find({"tipo": "cliente", "boletas_info": {"$exists": False}})
    for factura in cursor:
        try:
            snapshot = build_boletas_info_snapshot(factura.get("boletas", []), valor_boleta)
            facturas.update_one({"_id": factura["_id"]}, {"$set": {"boletas_info": snapshot}})
            count += 1
            print(f"[+SNAPSHOT] factura {factura['_id']}: {len(snapshot)} boleta(s).")
        except Exception as exc:
            print(f"[ERROR] factura {factura['_id']}: {exc}")
    return count


def migrar_historial_movimientos() -> int:
    """Migrate legacy `historial_pagos` into the unified `historial_movimientos` ledger.

    Existing payment entries are copied with `tipo: "pago"` (the net balance and
    `total_abonado` are unchanged because egresos/traslados did not exist yet).
    """
    if boletas is None:
        return 0
    pendientes = boletas.count_documents({MOVIMIENTOS_FIELD: {"$exists": False}, "historial_pagos": {"$exists": True}})
    if not pendientes:
        return 0
    boletas.update_many(
        {MOVIMIENTOS_FIELD: {"$exists": False}, "historial_pagos": {"$exists": True}},
        [
            {
                "$set": {
                    MOVIMIENTOS_FIELD: {
                        "$map": {
                            "input": {"$ifNull": ["$historial_pagos", []]},
                            "as": "p",
                            "in": {"$mergeObjects": ["$$p", {"tipo": {"$ifNull": ["$$p.tipo", MOV_PAGO]}}]},
                        }
                    }
                }
            },
            {"$unset": "historial_pagos"},
        ],
    )
    return pendientes


if __name__ == "__main__":
    migrados = migrar_historial_movimientos()
    if migrados:
        print(f"Historial migrado: {migrados} boleta(s) pasaron a {MOVIMIENTOS_FIELD}.")
    ok = verificar_indices()
    if ok:
        print("Optimización de índices completada correctamente.")
        # TTL index for loginIntentos — auto-expire docs based on expira_en field.
        if login_intentos is not None:
            try:
                existing = {idx["name"] for idx in login_intentos.list_indexes()}
                if "expira_en_1" not in existing:
                    login_intentos.create_index("expira_en", name="expira_en_1", expireAfterSeconds=0)
                    print("[+TTL]   login_intentos.expira_en_1 (auto-expire)")
                else:
                    print("[OK]     login_intentos.expira_en_1")
            except Exception as exc:
                print(f"[ERROR]  login_intentos TTL index: {exc}")
        backfilled = backfill_boletas_info()
        if backfilled:
            print(f"Snapshots boletas_info generados para {backfilled} factura(s) de cliente.")
        config = get_config()
        valor_boleta = int(config.get("valor_boleta", 10000) or 10000)
        sync_ticket_statuses(valor_boleta)
        print("Estados de boletas recalculados.")
    else:
        raise SystemExit(1)
